# Generated by Django 3.1.3 on 2023-04-21 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choice_text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_text',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='chocies',
        ),
        migrations.AddField(
            model_name='choice',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='course',
            name='exam',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='grade_point',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='submission',
            name='choices',
            field=models.ManyToManyField(default='', to='onlinecourse.Choice'),
        ),
        migrations.AlterField(
            model_name='question',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='onlinecourse.course'),
        ),
    ]
